#include<stdio.h>

#include<maht.h>

int main() {
        long int a[10], j, k,
            while (1) {
                for (i = 0; i <= 2; i++)
                    scanf("%ld", & a[i]);
                if ((a[0] == 0) && (a[1] == 1) && (a[2] == 0))
                    break;
                else {
                    b = 3 - 1;
                    for (j = 0; j < b; j++) {
                        for (k = 0; k < b - j; k++) {
                            if (n[k] > n[k + 1]) {
                                a = n[k];
                                n[k] = n[k + 1];
                                n[k + 1] = a;

                            }
                        }

                    }
                    return 0;

                }
            }